### ISSUE TITLE
The v. 2.3a randomizer still don't work

### ISSUE THREAD

**Issue by NotChainVerse** [LHY51/Worst-Calculator#2]
It work only 1 time and it just stop random the button

**Comment by LHY51** [comment]
There's 2 clocks and both should be on. So that shouldn't happen. Try unistalling and reinstalling.

**Comment by NotChainVerse** [comment]
I try that 5 times

**Comment by LHY51** [comment]
Found the issue. The clocks, when ticked, I both set it to the same interval. I fixed this by setting the second clock's interval by half. I'll repost. Sorry that you waited for so long.
